"""Initial migration User

Revision ID: d7e6edb9463b
Revises: 
Create Date: 2024-07-08 09:26:45.684628

"""
from typing import Sequence, Union

from alembic import op
from sqlalchemy import text

# revision identifiers, used by Alembic.
revision: str = 'd7e6edb9463b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("""
    CREATE TABLE IF NOT EXISTS public.users
    (   
        id integer NOT NULL GENERATED ALWAYS AS IDENTITY ( INCREMENT 1 START 1000 MINVALUE 1 MAXVALUE 2147483647 CACHE 1 ),
        email character varying(50) COLLATE pg_catalog."default" NOT NULL,
        password character varying(100) COLLATE pg_catalog."default" NOT NULL,
        type character varying(15) COLLATE pg_catalog."default",
        CONSTRAINT users_pkey PRIMARY KEY (id)
    )

    TABLESPACE pg_default;
    
    ALTER TABLE IF EXISTS public.users
        OWNER to admin;
    """))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(text("""
        DROP TABLE IF EXISTS public.users;
        """))
    # ### end Alembic commands ###
