"""Added user_role to UserProject

Revision ID: 32be52476ea1
Revises: bfeb10955729
Create Date: 2024-08-20 14:04:48.850525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32be52476ea1'
down_revision: Union[str, None] = 'bfeb10955729'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_projects', sa.Column('user_role', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users_projects', 'user_role')
    # ### end Alembic commands ###
